name: stalhub
description: "A Flutter-based company management system app for tasks, invoices, and customer support."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and Styling
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  intl: ^0.18.1
  flutter_screenutil: ^5.9.3

  # Supabase backend
  supabase_flutter: ^2.8.4

  # CSV Export
  uuid: ^4.0.0
  csv: ^5.0.2
  path_provider: ^2.1.2
  permission_handler: ^11.0.0

  # Date & time utilities
  flutter_datetime_picker_plus: ^2.1.0

  # Notifications
  onesignal_flutter: ^5.3.0
  firebase_core: ^2.27.0  
  http: ^1.1.0
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main
  shared_preferences: ^2.2.0


  # Webview for Supabase dependencies
  webview_flutter: ^4.4.1        # ✅ Add this
  webview_flutter_android: ^3.16.3
  webview_flutter_wkwebview: ^3.4.1

  # Optional: Snackbar/Dialogs/Toasts (your choice)
  fluttertoast: ^8.2.4
  bcrypt: ^1.1.3
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/stalwrites-logo.png
    - assets/images/dashboard-icon.png
    - assets/images/client-icon.png
    - assets/images/tasks-icon.png
    - assets/images/wallet-icon.png
    - assets/images/profile-icon.png

  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree-Regular.ttf
        - asset: assets/fonts/Figtree-Bold.ttf
          weight: 700
        - asset: assets/fonts/Figtree-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Figtree-Light.ttf
          weight: 300